name: docx_template
description: A Docx template engine.
version: 0.4.0
homepage: https://github.com/PavelS0/docx_template_dart
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: 3.6.1
  xml: ^6.5.0
  collection: ^1.18.0
  path: ^1.8.0
dependency_overrides:
  archive:
    git: https://github.com/alihassan143/archive.git
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
