name: ais_utils
description: Common UI widgets and utils for all clients of ais_voter.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  intl: any
  global_configuration: any
    #path: '../global_configuration-1.6.0'
  ntp: any
  ais_model:
    path: '../ais_model'
  auto_size_text: any
  #window_size:
  #  path: '../window_size'
  #transparent_pointer: any
  select2dot1: any
  collection: ^1.18.0
  dropdown_search: 6.0.2

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
