name: services
description: Http/Websocket server for ais voter system
version: 1.05.14

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  conduit: any
  uuid: any
  mime: any
  intl: any
  ntp: any
  enum_to_string: any
  ais_model:
    path: '../clients/client_plugins/ais_model'
  mutex: ^3.0.0
  path: ^1.8.0
  #threading: any
  pedantic: any
  package_info_plus: any
  yaml: any
  collection: ^1.18.0

#dependency_overrides:
#  postgres: ^2.1.1

#pub run aqueduct db generate
#pub run aqueduct db upgrade