name: services
description: Http/Websocket server for ais voter system
version: 1.05.14

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  aqueduct: 3.3.0+1
  uuid: any
  mime: any
  intl: any
  ntp: ^2.0.0
  enum_to_string: any
  ais_model:
    path: '../clients/client_plugins/ais_model'
  dependencies:
  mutex: ^3.0.0
  path: ^1.8.0
  threading: any
  pedantic: any
  package_info_plus: any
  yaml: any

dependency_overrides:
  postgres: ^2.1.1

#pub run aqueduct db generate
#pub run aqueduct db upgrade