name: services
description: AIS Voter Http/WebSocket server.
version: 1.05.14
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  conduit: ^5.1.0
  uuid: any
  mime: any
  intl: any
  ntp: any
  enum_to_string: any
  ais_model:
    path: '/home/user/Desktop/AIS/AIS_voter_Novgorod/AIS_voting/src/clients/client_plugins/ais_model'
  path: ^1.8.0
  yaml: any
  collection: ^1.18.0