name: services
description: Http/Websocket server for ais voter system
version: 1.05.14
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  conduit: ^5.1.0
  uuid: any
  mime: any
  intl: any
  ntp: any
  enum_to_string: any
  ais_model:
    #path: '../clients/client_plugins/ais_model'
    path: '/home/user/Desktop/AIS/AIS_voter_Novgorod/AIS_voting/src/clients/client_plugins/ais_model'
  mutex: ^3.0.0
  path: ^1.8.0
  #threading: any
  #pedantic: any
  #package_info_plus: any
  yaml: any
  collection: ^1.18.0


#dependency_overrides:
#  postgres: ^2.1.1

#pub run aqueduct db generate
#pub run aqueduct db upgrade