name: deputy
description: AIS deputy client application.
publish_to: 'none'
version: 1.05.21

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: 3.0.1
  http: any
  ntp: ^2.0.0
  provider: any
  global_configuration: any
    #path: '../client_plugins/global_configuration-1.6.0'
  synchronized: ^3.0.0
  enum_to_string: any
  uuid: any
  intl: any
  ais_model:
    path: '../client_plugins/ais_model'
  ais_utils:
    path: '../client_plugins/ais_utils'
  window_to_front:
    path: '../client_plugins/window_to_front'
  virtual_keyboard_multi_language: any
  window_size:
    path: '../client_plugins/window_size'
  desktop_window:
    git:
      url: https://github.com/mix1009/desktop_window.git
  window_manager: ^0.2.3
  auto_size_text: ^3.0.0
  google_fonts: any
  dropdown_search: ^0.6.0
  package_info_plus: ^4.2.0
  sdp_transform: ^0.3.2
  statsfl: ^2.3.0
  pdfrx: ^1.0.72
  collection: ^1.18.0

flutter:
  uses-material-design: true
  assets:
  - assets/cfg/
  - assets/fonts/
  - assets/shellScripts/
  - assets/streamPlayer/
  - assets/images/emblem.png
  - assets/images/storeboard_stub.png

#export PATH=/home/vladimir/Desktop/Flutter/depot_tools:$PATH
#export PATH=/home/vladimir/Desktop/Flutter/flutter/bin:$PATH
#flutter run --local-engine=/home/vladimir/Desktop/Flutter/engine/src/out/host_debug_unopt --no-sound-null-safety -v