name: ais_file_server
description: Http file server for ais voter system
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  conduit:
    path: '/home/user/Desktop/AIS/AIS_voter_Novgorod/AIS_voting/src/clients/client_plugins/conduit-5.1.3'
  mime: any
  http_server: any
  ais_model:
    path: '/home/user/Desktop/AIS/AIS_voter_Novgorod/AIS_voting/src/clients/client_plugins/ais_model'
  

