name: ais_model
description: models for client applications

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0
  intl: any
  enum_to_string: 1.0.14

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.1.0
  json_serializable: ^3.2.0
  
dependency_overrides:
  analyzer: '0.39.14'