name: loader
description: AIS VOTER Agenda loader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker: any
  uuid: any
  csv: any
  http: any
  path: any
  intl: any
  global_configuration: any
  ais_model:
    path: '../client_plugins/ais_model'
  ais_utils:
    path: '../client_plugins/ais_utils'
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/cfg/
