name: ais_agenda
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: any
  flutter_form_builder: ^7.3.0
  
  #pwa: ^0.2.1
  global_configuration: ^1.6.0
  provider: any
  virtual_keyboard_multi_language: ^0.2.4
  horizontal_data_table: ^4.1.1
  flutter_fancy_tree_view: ^0.5.1+1
  time_planner: ^0.0.4
  form_builder_validators: ^8.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/cfg/