name: operator_panel
description: AIS Voter Operator Panel.
publish_to: 'none'
version: 1.05.17

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  web_socket_channel: any
  http: any
  provider: any
  horizontal_data_table: any
  intl: any
  uuid: any
  enum_to_string: any
  flutter_colorpicker: any
  global_configuration: any
  csv: any
  ntp: ^2.0.0
  media_kit: any
  media_kit_libs_audio: any
  dropdown_search: 6.0.2
  ais_model:
    path: '../client_plugins/ais_model'
  ais_utils:
    path: '../client_plugins/ais_utils'
  auto_size_text: ^3.0.0
  google_fonts: any
  aligned_dialog: ^0.0.6
  drag_and_drop_lists: any
  transparent_pointer: ^1.0.0
  file_selector: any
  package_info_plus: any
  select2dot1: ^2.0.7
  collection: ^1.18.0
  docx_template:
    path: '../client_plugins/docx_template_dart-master'
    
dependency_overrides:
  archive:
    git: https://github.com/alihassan143/archive.git
   
flutter:
  uses-material-design: true
  assets:
  - assets/cfg/
  - assets/fonts/
  - assets/templates/