name: agenda
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: any
  uuid: 2.2.2
  path: any
  intl: any
  ais_model:
    path: '../client_plugins/ais_model'
  ais_utils:
    path: '../client_plugins/ais_utils'
  drag_and_drop_lists:
    path: '../client_plugins/DragAndDropLists-master'
  dropdown_search: ^0.6.0  
  charset: ^2.0.1
  windows_single_instance: ^1.0.1
  window_manager: ^0.3.7
  filepicker_windows: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/data/povestka_example/
  - assets/data/povestka_example/0/
