name: storeboard
description: AIS storeboard client.
publish_to: 'none'
version: 1.04.26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  http: any
  ntp: ^2.0.0
  web_socket_channel: any
  ais_model:
    path: '../client_plugins/ais_model'
  ais_utils:
    path: '../client_plugins/ais_utils'
  window_manager: ^0.2.3
  provider: any
  window_size:
    path: '../client_plugins/window_size'
  google_fonts: any
  dropdown_search: ^0.6.0
  media_kit: any
  media_kit_libs_audio: any
  uuid: any
  package_info_plus: ^4.2.0
  flutter_webrtc: #^0.9.48+hotfix.1
    path: '../client_plugins/flutter-webrtc-main/'
  statsfl: ^2.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/cfg/
  - assets/fonts/
  - assets/shellScripts/
  - assets/streamPlayer/

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

