name: storeboard
description: AIS Voter Storeboard client.
publish_to: 'none'
version: 1.04.26

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  http: any
  ntp: ^2.0.0
  web_socket_channel: 3.0.1
  ais_model:
    path: '../client_plugins/ais_model'
  ais_utils:
    path: '../client_plugins/ais_utils'
  window_manager: ^0.2.3
  provider: any
  window_size:
    path: '../client_plugins/window_size'
  google_fonts: any
  dropdown_search: 6.0.2
  media_kit: any
  media_kit_libs_audio: any
  uuid: any
  package_info_plus: ^4.2.0
  flutter_webrtc: any
    #path: '../client_plugins/flutter-webrtc-main'
  statsfl: ^2.3.0
  collection: ^1.18.0

dependency_overrides:
   win32: 5.5.4
   archive: 3.6.1

flutter:
  uses-material-design: true
  assets:
  - assets/cfg/
  - assets/fonts/
  - assets/shellScripts/
  - assets/streamPlayer/

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

